#include<stdio.h>
 int main()
    {
        int a,b,c,d,e,f,g;

        printf("enter value of a :");
        scanf("%d",&a);
        printf("enter value of b :");
        scanf("%d",&b);
        printf("enter value of c :");
        scanf("%d",&c);
        printf("enter value of d :");
        scanf("%d",&d);
        printf("enter value of e :");
        scanf("%d",&e);
        printf("enter value of f :");
        scanf("%d",&f);
        printf("enter value of g :");
        scanf("%d",&g);

        (a>b)
            ?(a>c)
                ?(a>d)
                    ?(a>e)
                        ?(a>f)
                            ?(a>g)
                                ?printf("a is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")

                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                    :(d>e)
                        ?(d>f)
                            ?(d>g)
                                ?printf("d is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                :(c>d)
                    ?(c>e)
                        ?(c>f)
                            ?(c>g)
                                ?printf("c is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                    :(d>e)
                        ?(d>f)
                            ?(d>g)
                                ?printf("d is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
            :(b>C)
                ?(b>d)
                    ?(b>e)
                        ?(b>f)
                            ?(b>g)
                                ?printf("b is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                ?printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                    :(d>e)
                        ?(d>f)
                            ?(d>g)
                                ?printf("d is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                :(c>d)
                    ?(c>e)
                        ?(c>f)
                            ?(c>g)
                                ?printf("c is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                    :(d>e)
                        ?(d>f)
                            ?(d>g)
                                ?printf("d is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max")
                        :(e>f)
                            ?(e>g)
                                ?printf("e is max")
                                :printf("g is max")
                            :(f>g)
                                ?printf("f is max")
                                :printf("g is max");
        

    }